### ISSUE TITLE
What is the bios version?

### ISSUE THREAD

**Issue by yuanhsuan** [theHari08/MSI-MAG-X570-TOMAHAWK-WIFI-Hackintosh#1]
I still have problems to install with this EFI

**Comment by theHari08** [comment]
Latest stable one in product support page ie. 7C84v14

**Comment by yuanhsuan** [comment]
What is the  subvendor of your RX580? I think my XFX Rx580 2304sp didn’t work with MacOS.

**Comment by theHari08** [comment]
> What is the subvendor of your RX580? I think my XFX Rx580 2304sp didn’t work with MacOS.

I use Sapphire Pulse Radeon RX 580 8G GDDR5

**Comment by titianqx** [comment]
> Latest stable one in product support page ie. 7C84v14

can u share the bios setting? 

i also have some probelms with this efi. 

i followed the oc guide and finally sounds does not work. so i searched this repo.

thanks for sharing.

**Comment by titianqx** [comment]
I updated my bios and set bios as this [bios seting](https://github.com/barrrrt/AMD-3900x_MEG-MSI-Unify-X570_AMD-X5700XT). and all thing is perfect expect memory. mine memory is 16*2 but sys info shows 64.
