### ISSUE TITLE
Did you get sound working? 

### ISSUE THREAD

**Issue by lucky13820** [theHari08/MSI-MAG-X570-TOMAHAWK-WIFI-Hackintosh#2]
I see some people say the audio won’t work with AppleALC, only VodooHDA. Wondering how did you get your sound working.

**Comment by theHari08** [comment]
I use HDMI audio and it works good

**Comment by TheVinhLuong** [comment]
@lucky13820 Did you make it work with VodooHDA? Thanks

**Comment by theHari08** [comment]
> @lucky13820 Did you make it work with VodooHDA? Thanks

No. AppleALC

**Comment by TheVinhLuong** [comment]
> > @lucky13820 Did you make it work with VodooHDA? Thanks
> 
> No. AppleALC

@theHari08 Internal Speaker is not working in my case, only HDMI audio works. Btw nice configuration you have there, thanks for sharing.
